import type { Metadata } from "next";
import { Manrope } from 'next/font/google';

import "./globals.css";
import AosProvider from "./components/shared/AosProvider/AosProvider";
import Navbar from "./components/shared/navbar/Navbar";
import Footer from "./components/shared/Footer/Footer";

const manrope = Manrope({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} antialiased`}
      >
        <Navbar/>
          <AosProvider>
            {children}
          </AosProvider>
        <Footer/>
      </body>
    </html>
  );
}
